### ISSUE TITLE
Feature: Ground Station Filter

### ISSUE THREAD

**Issue by Squire298** [wiedehopf/tar1090#101]
Hi,

could there be a function added to filter out ground station in the config?

thanks
![Screenshot_2](https://user-images.githubusercontent.com/23255124/107844878-30c14e00-6e3c-11eb-8b92-3537741a5029.png)

**Comment by wiedehopf** [comment]
There is already an option in the settings.

**Comment by Squire298** [comment]
for ADS-B noTP?

**Comment by wiedehopf** [comment]
Just test the stuff settings in the gear wheel menu.
