### ISSUE TITLE
togglePersistence vs Trail width

### ISSUE THREAD

**Issue by utilisateur47** [wiedehopf/tar1090#102]
Hello
Should an aircraft's trail width decrease and increase as Persistence mode is toggled on or off?
Is this by design, I'm not so sure?
For me, this happens regardless of any other option selected.
I couldn't locate any info on this anywhere so I had to ask.
New to GIT so go easy please.
Thank you.
_ut

**Comment by wiedehopf** [comment]
That's by design yes as it was originally used manually what ptracks is now.
I suppose i could rewire that.

**Comment by utilisateur47** [comment]
Thanks for the reply. 
That's cool, it makes sense to me now.
I'm just a gui user, so was a little unintuitive to me.
Rewire is always an option, is it necessary?
Probably not but that might bug me.
Cheers
