### ISSUE TITLE
Show numbers of planes in the Title (Feature request)

### ISSUE THREAD

**Issue by Dtrieb** [wiedehopf/tar1090#104]
On the "normal" dump1090 you see the spotted plans in brackets. (See screenshot)
Could you add this also?

![chrome_2021-02-23_15-55-28](https://user-images.githubusercontent.com/3650284/108861510-95746980-75ef-11eb-81a9-48dd4ac936dd.png)

**Comment by wiedehopf** [comment]
See the config.js please as explained in the readme.
