### ISSUE TITLE
ol-scale-line-inner vs "Site position and range rings"

### ISSUE THREAD

**Issue by utilisateur47** [wiedehopf/tar1090#107]
Hello again
Should these scales be accurate to each other?
I notice that the ol-scale-line-inner scale seems a little low compared to the range rings.
It also seems even lower when zoomed out more.
This occurs for my location, here in the UK.
I see Openlayers does some scale correction that varies with latitude.
This feature might be insignificant but wouldn't you expect this to be accurate?
Thought you'd like to know about this, if you weren't already aware.
Thanks for product btw, way better than all the paid options out there.
-ut

**Comment by wiedehopf** [comment]
I'd say the scale is for the middle of the map.

It's the mercator projection, distances further north from west to east will be shorter.
