### ISSUE TITLE
Russian Military

### ISSUE THREAD

**Issue by jamesBNR** [wiedehopf/tar1090#109]

**Comment by wiedehopf** [comment]
No i said military ranges.

This isn't a range but a collection of serials.
So this would go into the DB ... let's see if it fits in there without type.

**Comment by wiedehopf** [comment]
Yeah so ... you'd need to only send me those which don't have the correct data yet.

Just plug the registration or hex into the search box: https://globe.adsbexchange.com/
If you get the data you have there ... then there is no correction needed.
So .. only corrections to the DB please.

**Comment by wiedehopf** [comment]
Thank you for the list it was incorporated into the database :)
