### ISSUE TITLE
Initial web page has no flights/requires reload

### ISSUE THREAD

**Issue by RonRN18** [wiedehopf/tar1090#118]
Every time I go to the /tar1090 web page, I get the map and everything but absolutely zero flights or flight data listed. Every time I have to reload the page and once I do, I then get all of the aircraft and flight data displayed as expected. This is a minor annoyance but still an annoyance and curious why it initially loads without that data.

**Comment by wiedehopf** [comment]
Please open the browser / developer console and provide a screenshot of the Log when the data doesn't load.
https://support.monday.com/hc/en-us/articles/360002197259-How-to-Open-the-Developer-Console

**Comment by wiedehopf** [comment]
closing due to no answer.
