### ISSUE TITLE
Links are blue on black in dark mode

### ISSUE THREAD

**Issue by Nibb31** [wiedehopf/tar1090#119]
The new dark mode is absolutely gorgeous, but links appear unreadable in blue on a black background. The table on the right is still readable, but the blue isn't optimal.

I am using Firefox 87 for Ubuntu.
![Screenshot from 2021-04-13 13-41-14](https://user-images.githubusercontent.com/9588895/114547026-2e257e00-9c5e-11eb-8b04-02a27665d2c0.png)

**Comment by wiedehopf** [comment]
https://github.com/wiedehopf/tar1090/commit/28acd239e8711dd8a83f35eb07ba4ba0631a2ed6
