### ISSUE TITLE
Webinterface does not load

### ISSUE THREAD

**Issue by dxmekch** [wiedehopf/tar1090#12]
I'm running dump1090-1.15 and piaware output to http://192.168.1.X:30053/ajax/aircraft works, but the browser (apache2 as webserver) can not load tar1090. I think I need to add a apache2 config file, but I'm somehow struggling doing it myself. Do I need to include the files in /usr/local/share/tar1090/html?

Thanks for your help

**Comment by wiedehopf** [comment]
I don't support apache.
Only nginx and lighttpd are supported.

You could always run lighttpd on a port that's not 80 or already taken.

If you want to make Apache work, you'll have to read either the nginx or lighttpd config file and figure it out yourself.
