### ISSUE TITLE
Retain favicon.ico during install script

### ISSUE THREAD

**Issue by kevdel** [wiedehopf/tar1090#124]
Would it be possible to add the following into the install script to keep any personalized favicon.ico on local installs?

Around line 262 in install.sh
    mv "$html_path/favicon.ico" "$TMP/favicon.ico" 2>/dev/null || true

**Comment by wiedehopf** [comment]
Just write yourself a wrapper script that replaces the favicon after the install script runs?

**Comment by kevdel** [comment]
wrapper script it is..

**Comment by wiedehopf** [comment]
```/usr/local/share/tar1090/customIcon.png```

how about that?
If that file is present it uses it as an icon

debad046d1bbb04b37080cc6357ae45f8594ca80
