### ISSUE TITLE
FATAL: could not find aircraft.json in any of the usual places!

### ISSUE THREAD

**Issue by ghost** [wiedehopf/tar1090#126]
[img]https://upload.cc/i1/2021/05/15/f37gq4.png
What should I do? The installation process is shown in the figure

**Comment by wiedehopf** [comment]
tar1090 is not standalone.

https://github.com/wiedehopf/adsb-wiki/wiki/Raspbian-Lite:-ADS-B-receiver

**Comment by raleighlittles** [comment]
@wiedehopf your response to that comment doesn't really resolve the issue. 

I'm getting this error after trying to install your readsb script, I'm running a Raspberry Pi with the Flightradar pi24 image, and a HackRF One as my SDR.

**Comment by wiedehopf** [comment]
readsb doesn't support hackrf, it's 99% for rtl-sdr or to receive data via network in beast format.
