### ISSUE TITLE
Aircraft misidentification ?

### ISSUE THREAD

**Issue by utilisateur47** [wiedehopf/tar1090#127]
Hello
I notice that the UK RAF "BAE Systems Hawk T1" is being identified as "BRITISH AEROSPACE T-45 Goshawk".
This maybe due to them both having the same type: "Hawk".
The UK have no T-45 aircraft.
Just FYI.
_ut

**Comment by wiedehopf** [comment]
You're being unspecific not providing a hex number.

**Comment by utilisateur47** [comment]
If you need it, try this one: 43C40A.
Thank you.
