### ISSUE TITLE
Plane Route (Feature Request)

### ISSUE THREAD

**Issue by HanSyt** [wiedehopf/tar1090#128]
Using dump1090-fa with VirtualRadar gives me the flight route ie: LHR-AMS, etc.
Is is possible to build this into tar1090? Or if it is already in it, where can I find it.
![image](https://user-images.githubusercontent.com/56794786/119646138-1b869300-be1f-11eb-9ce0-547920eff3a1.png)

**Comment by wiedehopf** [comment]
no that's not possible.
