### ISSUE TITLE
Missing Type Code and Registration in latest Safari on OS X

### ISSUE THREAD

**Issue by rice3253** [wiedehopf/tar1090#130]
Hello,

The type code are missing on Safari on OS X, a Chrome browser on the same machine shows the type code and picture. Chrome, Safari, and OS X have all been updated to the latest versions.

I am noticing I am getting the following console message in Safari that is not present in Chrome: a3a0ed: Database load error: parsererror at URL: db-1620696395/A.js
planeObject_1620696395.js:2084

The "a3a0ed" string is the Hex ID of the aircraft, and varies with each error message in the JavaScript Console log.

<img width="346" alt="Screen Shot 2021-05-27 at 6 19 21 PM" src="https://user-images.githubusercontent.com/68102429/119908465-4274c000-bf18-11eb-96b5-68b09cb828a8.png">
<img width="196" alt="Screen Shot 2021-05-27 at 6 19 34 PM" src="https://user-images.githubusercontent.com/68102429/119908468-430d5680-bf18-11eb-8229-60139329e154.png">

**Comment by wiedehopf** [comment]
So ... what is the latest version you update to ...?

Also show the full output on the browser console if you're already looking at it.

**Comment by rice3253** [comment]
[Console.txt](https://github.com/wiedehopf/tar1090/files/6579958/Console.txt)
I have attached the console log, the version number shows as 1622573508.

**Comment by wiedehopf** [comment]
That means you installed a locally modified version if i'm not mistaken?

If that browser can't handle the gzip encoding ... really can't help that.
So you'd have to go to the network tab ... reload the page and check the response headers for one of those database files.
Maybe there are duplicated headers that can cause issues.

It's proably a lighttpd issues .. so check the lighttpd logs if the server reports any issues on startup.
