### ISSUE TITLE
Persistent filters (Feature Request)

### ISSUE THREAD

**Issue by sxdjt** [wiedehopf/tar1090#14]
It would be great it we could set filters and have them persist from one session to the next.

Use case/example:  I don't care about aircraft on the ground, so I set an altitude filter to exclude anything under 10 feet.  

The filter works as expected, but I have to set it every time I view the site.

**Comment by rin67630** [comment]
+1

additionally it would probably make sense to erase tracks on map each time a filter is set: currently the tracks that are on the map before the filter went in operation stay forever on the map.

**Comment by wiedehopf** [comment]
The track will only stay on the map until the aircraft is deselected.

But seems in case you have all trails (all aircraft selected) enabled, that case isn't properly handled.
