### ISSUE TITLE
Question: How to submit missing/wrong DB entries?

### ISSUE THREAD

**Issue by sgofferj** [wiedehopf/tar1090#141]
As the title says... What's the process?
OH-CAY keeps popping up on my screen and she doesn't seem to be in the DB. Her ICAO hex ID would be "460560". She is a club plane of Jukolan Pilotit and does voluntary wildfire watch and SAR flights.
https://www.planespotters.net/photo/1092071/oh-cay-private-cessna-172p-skyhawk-ii

**Comment by wiedehopf** [comment]
adsbexchange discord, there is a channel called registration-db

**Comment by sgofferj** [comment]
Oh well... Discord demands a mobile phone number for registration, so nothing for me.

**Comment by wiedehopf** [comment]
That should depend on the server, as far as i know you don't need phone verification for our server.

**Comment by sgofferj** [comment]
Unfortunately, you need for the discord account.
