### ISSUE TITLE
jetphotos not working

### ISSUE THREAD

**Issue by Squire298** [wiedehopf/tar1090#142]
the planes in my area have two or three letters then a - then numbers ZK-TPT

But jetphotos are trying to do ZKTPT and there is no such photo because the addressing is wrong

Simple fix?

**Comment by Squire298** [comment]
also how to make it take a random photo from jetphotos and display it?

**Comment by wiedehopf** [comment]
jetphotos is not used in tar1090.

planespotters.net is used and they very likely just don't have pictures for aircraft in your area.
