### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by utilisateur47** [wiedehopf/tar1090#144]
Hello
I noticed an error while viewing today.
It regards the following aircraft data.
You know the correct spelling of the word Hawk, as it is correct for other H60 aircraft.

DUKE17
Hex: AE50E2 
Reg. 10-20311
United States
DB flags:military
Type: H60
Sikorsky UH-60M Black Hoawk
Type Desc. H2T
Squawk:3300

Thanks.
_ut

**Comment by wiedehopf** [comment]
unimportant.
