### ISSUE TITLE
[Enhancement Request] Add Fourth Label Extension for Registration+Type+Altitude+Speed

### ISSUE THREAD

**Issue by rdmcvicar** [wiedehopf/tar1090#145]
...or adding the speed to the one that already has the other three.

I find myself toggling around to gather those pieces of information as I watch Fisk arrivals to EAA Air Venture / Oshkosh, WI USA.

![image](https://user-images.githubusercontent.com/24771022/126871398-9c2e91f1-7385-42e0-a3dd-4c57247e71ab.png)

I love this tool and appreciate all the work and consideration.  Thanks!

**Comment by wiedehopf** [comment]
Use the table on the right maybe?
Columns there can be customized.

If anything labels would need to be completely customizable.
But i don't really care for that, so unless someone else programs it, not happening.

**Comment by rdmcvicar** [comment]
Fair enough; I use the columns plenty, but am certainly taking it a step or two further with this request as to focusing on the aircraft screen.

Thanks again for this super tool, and your (also fast) consideration of changes.  Great work.
