### ISSUE TITLE
Alenia C-27J

### ISSUE THREAD

**Issue by Henry2o1o** [wiedehopf/tar1090#146]
![image](https://user-images.githubusercontent.com/6131799/132095292-0cc5fb52-df6b-45f7-8a2b-e2c968f1e8ab.png)

Alenia C-27J
![image](https://user-images.githubusercontent.com/6131799/132095325-9380356b-49ba-4d71-ab8a-4a36d4834299.png)

**Comment by wiedehopf** [comment]
click the image, see where it comes from.
Not this project that is the issue.

**Comment by Henry2o1o** [comment]
OK , DANKE
