### ISSUE TITLE
GERMAN TRANSLATION

### ISSUE THREAD

**Issue by Henry2o1o** [wiedehopf/tar1090#153]
Just a question, could add a translation, for example, German?

**Comment by wiedehopf** [comment]
Translations are a chore to maintain, so no i will not do that.

If you don't understand something, try google translate or similar services.

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/156189238-fef16451-7544-462d-b03f-598f78a61db5.png)

what do these marks mean
