### ISSUE TITLE
tar1090 garbeled in HTML

### ISSUE THREAD

**Issue by SM6FMB** [wiedehopf/tar1090#157]
My Tar1090 seems to broken something so only HTML GUI not graphic GUI seen after system crash.
I have removed and reinstalled in RPI but nothing helps! I am not a Linux guy, only Windows.

**Comment by wiedehopf** [comment]
That's not very much info, no screenshot nothing.
Please go to this discord, i can see what i can do over there, just post a screenshot with the issue in the tech support channel.
https://discord.com/invite/n9dGbkTtZm
