### ISSUE TITLE
Hiding scale and copyright text from the UI

### ISSUE THREAD

**Issue by chvvkumar** [wiedehopf/tar1090#158]
Hello guys, 

I am trying to make a small display for tar1090 on my desktop. I managed to tune it to my liking except for the scale display and the map copyright information (photo below). Is there a way to hide both of these?

![image](https://user-images.githubusercontent.com/16548147/143133797-b97af634-677a-4320-866a-648e7591f840.png)

**Comment by wiedehopf** [comment]
It's not allowed to hide the copyright of the maps.

There are no options for this ... it is removable in the javascript but i won't assist with that.

**Comment by chvvkumar** [comment]
> It's not allowed to hide the copyright of the maps.
> 
> There are no options for this ... it is removable in the javascript but i won't assist with that.

Understood on the copyright. What about the scale display?

**Comment by wiedehopf** [comment]
I'd have to look at the source where it's added.
You're doing custom stuff, search for it yourself.

**Comment by wiedehopf** [comment]
1892             new ol.control.ScaleLine({units: DisplayUnits})                                                                        
script.js

**Comment by chvvkumar** [comment]
I did look through the documentation but could not find anything related to waht I was looking for.

Appreciate the reference to the code fragment for scale, that is a good jumping off point.
