### ISSUE TITLE
[Bug] Label extensions always show speed in "knots"

### ISSUE THREAD

**Issue by joberreiter** [wiedehopf/tar1090#160]
### Actual behaviour
Label extension shows always speed in "knots", even if units are set to "metric" or "imperial".
In the example image below, the speed is shown as "119", where the additional mouse hover popup window shows "221 km/h":
![grafik](https://user-images.githubusercontent.com/13220647/147480778-ba083311-7db4-4c65-9814-ac606660ff23.png)

### Expected behaviour
Label extension display should follow the unit setting.
If a permanent "knots" display is the desired behaviour (regardless of the unit setting), add a "kt" to the displayed value to make it clear.

**Comment by wiedehopf** [comment]
Please only file bugs after updating, thank you.

**Comment by joberreiter** [comment]
You are right, I'm sorry.
Have run the update last week, but maybe this was a caching issue.

I close the issue, I confirm this is fixed.

**Comment by wiedehopf** [comment]
No problem, seems i was a bit grumpy 2 days ago :)
Yeah i only recently changed something in the code and thanks for confirming it's fixed.
