### ISSUE TITLE
Country flag of Switzerland is squeezed

### ISSUE THREAD

**Issue by by** [wiedehopf/tar1090#168]
The original country flag from https://dynamospanish.com/flags/countries/switzerland/ is square (as it should be); at https://github.com/wiedehopf/tar1090/blob/master/html/flags-tiny/Switzerland.png, it is stretched to the rectangular format of the other flags

**Comment by wiedehopf** [comment]
https://dynamospanish.com/flags/countries/switzerland/

The tiny flag is the stretched already.
It's not an issue.

**Comment by wiedehopf** [comment]
gimp to the rescue

**Comment by by** [comment]
Maybe use this one with transparent parts left&right as the entire flag is square:
![Switzerland_square](https://user-images.githubusercontent.com/335425/156985811-d62bf90e-efad-4b06-8cdb-42c758e250cd.png)
.

**Comment by wiedehopf** [comment]
no it's fine now.
