### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by FrogCF** [wiedehopf/tar1090#172]
Hello, 

There seems to be a problem with the config? What ever u change within the config and then save it. I reload the radar and press CTRL +f5 the changes don't work.

It seems like it's ignoring teh config file and loading the default configs it's not changing anything. 

Can any one please able to shed some light on this.

Many thanks?

**Comment by wiedehopf** [comment]
The browser will remember certain settings.
config.js will only matter if the toggle hasn't been used.

Reset all settings in the settings box, then your config.js changes will matter.
