### ISSUE TITLE
Flight number instead of callsign?

### ISSUE THREAD

**Issue by mensa84** [wiedehopf/tar1090#178]
Hello,

not really any issue, but don't know where else to ask questions about this plugin.

Is it possible to show instead of the callsign the flight number?
Is it also possible to link to FR24 website if I click on a flight detail? I think dump1090 does this, or?

**Comment by wiedehopf** [comment]
Flight number isn't broadcast on 1090 MHz. Callsign is.

There are FA links available via a config setting.
FR24 can't be properly linked by hex or registration or callsign.
If you know a technical implementation you are free to make a pull request.

**Comment by wiedehopf** [comment]
Oh and of course there are also adsbexchange links available via a config setting if i'm not mistaken.

**Comment by mensa84** [comment]
Thank you, I enabled FA links by that command `sudo sed -i -e 's?.*flightawareLinks.*?flightawareLinks = true;?' /usr/local/share/tar1090/html/config.js` and refreshed by F5.

But where will I have to click then exactly to open FA?

**Comment by wiedehopf** [comment]
click the reg or something, i don't even remember.

**Comment by mensa84** [comment]
Not working :(

**Comment by mensa84** [comment]
BTW: Do you know why sometimes I can see an airplane in the list on the right, but not showing up in the map?
I had that for example with a helicopter in the last week.
