### ISSUE TITLE
Feature request: Change html title when an aircraft is selected

### ISSUE THREAD

**Issue by jithware** [wiedehopf/tar1090#191]
Would be nice when you select an aircraft it changes the html title to the aircraft selected. For example:

```<title>ADS-B Exchange - tracking 13840 aircraft</title>```

_Aircraft selected_

```<title>ADS-B Exchange - tracking CC07C9 </title>```

That way when you save a bookmark, the bookmark will be named from the aircraft.

**Comment by wiedehopf** [comment]
hmmmm maybe

**Comment by wiedehopf** [comment]
No, i'd put the hex code, you'd want the callsign / registration ... really this naming will have to be up to you by renaming the bookmark.
