### ISSUE TITLE
Default sorting 

### ISSUE THREAD

**Issue by EDXWer** [wiedehopf/tar1090#199]
Is it possible to set the default sorting (distance, flight level) by URL?

**Comment by wiedehopf** [comment]
no.

**Comment by JRG1956** [comment]
Default column sort order seems to have changed recently.

With my tar1090 version installed 28 July, the data table defaults to being sorted lowest to highest on distance. With my version installed  10 August, the data table defaults to "random" - looking at the fully expanded data table I can't see that it is sorted on any of columns.

I'm not sure when the change started - but it has been in versions I've installed over at least the last week. Could it have something to do with the changes you made related to the max distance column when using /?pTracks  ?

**Comment by wiedehopf** [comment]
@EDXWer https://github.com/wiedehopf/tar1090/blob/master/README-query.md
