### ISSUE TITLE
Filters are not working anymore

### ISSUE THREAD

**Issue by autrion** [wiedehopf/tar1090#202]
If I select e.g. filter by DB flag "military" I have the same amount of planes on screen like without the filter. Seems that this issue is also with all other filters.
![Clipboard001](https://user-images.githubusercontent.com/5623872/194043874-d24ef010-92a7-4fdc-af96-2962aba9428f.png)
![Clipboard002](https://user-images.githubusercontent.com/5623872/194043885-627ea0bf-c666-4502-9d44-1bd7a3d3c0c0.png)

**Comment by BebeMischa** [comment]
works fine here on latest Firefox, all adsb stuff up to date.

**Comment by wiedehopf** [comment]
you need to click filter.
