### ISSUE TITLE
How to uninstall upintheair feature

### ISSUE THREAD

**Issue by ggoodloff** [wiedehopf/tar1090#220]
is there a way to disable / uninstall the terrain outline from tar1090?

**Comment by wiedehopf** [comment]
Remove the file in the html folder.

**Comment by ggoodloff** [comment]
I've tried that and it still shows on the new user map.

**Comment by wiedehopf** [comment]
Possibly wrong html folder.

Provide more details if i'm misunderstanding.
Really nothing i can tell you beyond to delete the file in question.

**Comment by virtadpt** [comment]
Could it be a caching issue?  Try loading the URL in a private window or force a refresh.

**Comment by ggoodloff** [comment]
That's what it was.,. Looks good now
