### ISSUE TITLE
Show Mode-S Aircraft Icons on Map

### ISSUE THREAD

**Issue by 1CM69** [wiedehopf/tar1090#223]
Hi,
is there a way to show the mode-s aircraft icons on the map, I see that FR24 show the ADSB & Mode-S when I filter for my Radar and would like tar to match the FR24 display.

Thanks

**Comment by wiedehopf** [comment]
ModeS means there is no location.

Thus it can only be shown in the table.

**Comment by 1CM69** [comment]
Oh OK, interesting how FR24 website shows the aircraft icons for them. From my 11 Max ProOn 16 Feb 2023, at 13:38, wiedehopf ***@***.***> wrote:﻿
ModeS means there is no location.
Thus it can only be shown in the table.

**Comment by wiedehopf** [comment]
Probably last known location or something.
