### ISSUE TITLE
Missing argument in Url query?

### ISSUE THREAD

**Issue by ggoodloff** [wiedehopf/tar1090#227]
Am I missing an argument in my URL query that prevents the colorful altitude graph on the bottom from being displayed? I'm using a screen shot option on a headless chrome setup.

My URL query is currently:
&iconscale=1S&hideButtons&hidesidebar&screenshot&noIsolation&zoom=11&centerReceiver

On a Rpi I get the graph, on a Linux install I don't.

Really stumped:
![Screenshot_20230227_193711_Twitter](https://user-images.githubusercontent.com/122384058/221731494-e84133b4-227f-41a6-b138-32a295891270.jpg)
![Screenshot_20230227_193734_Twitter](https://user-images.githubusercontent.com/122384058/221731498-202908b6-e366-4354-bf06-3ceb228f198b.jpg)

**Comment by mpentler** [comment]
That is usually set by the settings cogwheel and I'm not sure if there's a url parameter for it.

**Comment by wiedehopf** [comment]
```
&altitudeChart=0
&altitudeChart=1
```
