### ISSUE TITLE
Empty "Hide" box

### ISSUE THREAD

**Issue by jidanni** [wiedehopf/tar1090#23]
There is an empty rectangle at the bottom of the screen with the label "Hide". Apparently some sort of failed ad.

**Comment by wiedehopf** [comment]
Well, if you run an adblocker / pihole you'll just have to deal with that ...

**Comment by jidanni** [comment]
OK, empty from "Hide in 20 seconds" all the way down till "Hide in 5
seconds" until five pictures finally appeared in it.

The rest of the site loaded within one second.

So the ad took 15 seconds.
