### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by Henry2o1o** [wiedehopf/tar1090#248]
Greetings, in the forum I can not write anything about it.

https://globe.adsbexchange.com/?icao=157dce

**URHOT - Hex: 157DCE**
Reg.: RF-97742
Russia
DB flags: military
Type: SU57
SUKHOI Su-57
Type Desc.: L2J
Squawk: 4450

Groundspeed: 181 km/h
Baro. Altitude: ▼ 564 m

**Comment by wiedehopf** [comment]
While adsbexchange uses tar1090, this project is not associated with them.
