### ISSUE TITLE
Can't start since update

### ISSUE THREAD

**Issue by jacobtilly** [wiedehopf/tar1090#257]
Hi,
I just updated the add-on, and when I try to start it, I now get the following:

 Image ghcr.io/maxwinterstein/homeassistant-adsb-multi-portal-feeder-aarch64:1.27.0 does not exist for addon_1e14b3fb_adsb-multi-portal-feeder 

What should I do?

**Comment by wiedehopf** [comment]
Wrong project.
That image might use this project but it's not my problem.
