### ISSUE TITLE
Wrong site position on TAR1090

### ISSUE THREAD

**Issue by DuccioNic** [wiedehopf/tar1090#260]
Hello everybody, the site position on the tar 1090 map it's wrong, but if I look ASDBexchange Map Anywhere, the site position it's correct, what file and parameters I have to check? thank you everybody

**Comment by DuccioNic** [comment]
https://github.com/wiedehopf/tar1090 I used this one

**Comment by DuccioNic** [comment]
I run it on PiAware os image

**Comment by wiedehopf** [comment]
Then your FA position is set incorrectly.

**Comment by DuccioNic** [comment]
But if i look in the flightaware site page the position its correct
