### ISSUE TITLE
Display in light mode

### ISSUE THREAD

**Issue by Henry2o1o** [wiedehopf/tar1090#264]
![image](https://github.com/wiedehopf/tar1090/assets/6131799/75961356-626f-4d89-b3b2-815ee8b232f4)

**Comment by Henry2o1o** [comment]
![image](https://github.com/wiedehopf/tar1090/assets/6131799/a06ff0d2-83aa-4910-97d1-3485cf23454c)
dark mode

**Comment by mpentler** [comment]
Is this the interface on adsbexchange @Henry2o1o ?

**Comment by wiedehopf** [comment]
indeed the wrong repo to post this issue.
