### ISSUE TITLE
config.js -> DisplayUnits = "metric"; 

### ISSUE THREAD

**Issue by anoo2niem** [wiedehopf/tar1090#265]
Hi,

I've just changed some values in config.js to my preference, all seem to be working fine.
Except DisplayUnits doesn't seem to work. It always stays on nautical, whether i set it to metric or imperial.

i've tried restarting the tar1090 service, aswell as clearing all cookies in browser, to no avail.

Any suggestions on how i can configure it to permanently display metric?

Thanks

**Comment by RundesBalli** [comment]
I can confirm that. I also noticed it some time ago.

**Comment by wiedehopf** [comment]
May i note anything but Aeronautical is an invalid setting in my opinion.
