### ISSUE TITLE
Who processes the corresponding types?

### ISSUE THREAD

**Issue by Henry2o1o** [wiedehopf/tar1090#267]
![image](https://github.com/wiedehopf/tar1090/assets/6131799/e9632c49-383b-45e4-8714-425403366bc7)

3EA383 shouldn't be a drone?

**Comment by stefslon** [comment]
This information comes from an offline aircraft registration database (aircraft.csv.gz), which, I think, comes from Mictronics. Similar databases are available from other sources as well. Another well-known one is by OpenSky, but they also list this particular registration number as DRON (https://opensky-network.org/aircraft-profile?icao24=3ea383) OpenSky allows you to submit edits if you know the correct type.
