### ISSUE TITLE
TAR1090 does not display correctly under macOS Sonoma 14.0 (23A344) and Safari 17.0 (19616.1.27.211.1)

### ISSUE THREAD

**Issue by by** [wiedehopf/tar1090#268]
Since the last update to macOS Sonoma 14.0 (23A344) and Safari 17.0 (19616.1.27.211.1), my local /tar1090 webpage does no longer display correctly (see attachment); /skyaware and /tar1090/?pTracks work without any issues.

Thanks for your help,
        Michael

P.S.: TAR1090 is the latest commit 5427b490fe37bc1251a32064392881c2dc9e2215

[TAR1090.pdf](https://github.com/wiedehopf/tar1090/files/12777258/TAR1090.pdf)

**Comment by wiedehopf** [comment]
Try /tar1090/?nowebgl

OS X not working due to webgl is not reallly my concern.

**Comment by by** [comment]
Thanks and yes, that does the trick. – BTW. It runs great on iOS 17.
