### ISSUE TITLE
Killing tar1090 (Question)

### ISSUE THREAD

**Issue by JayGgit** [wiedehopf/tar1090#271]
Thanks for looking at my problem. :)

I want to experiment with SDR++, but seem to run into an error where I'm guessing my RTL-SDR stick is already in use by tar1090. I've tried `sudo systemctl stop tar1090`, but it didn't seem to stop this software.

I'm also feeding to FR24 and FlightAware. How can I stop all these processes, so I can finally use SDR++?

**Comment by wiedehopf** [comment]
tar1090 is display side.

Stop readsb service or whatever decoder you're using, i can't know that. dump1090-fa / dump1090-mutability would be other candidates.
