### ISSUE TITLE
Suddenly no more planes

### ISSUE THREAD

**Issue by JoranJix** [wiedehopf/tar1090#273]
Suddenly my tar1090 instance stopped showing any planes.
I did not change anything. My receiver is working fine. Tested it on another computer.
I even installed the same instance on anothr raspberry piwithout a positive result.

I have no tried another SDR Stick to confirm. The problem stays.

**Comment by k8tek** [comment]
Curious if you updated to pi aware 9.  Mine stopped showing 1080 data as well. 978 data still works
