### ISSUE TITLE
Installation failed mv: cannot stat '/usr/local/share/tar1090/html': No such file or directory 

### ISSUE THREAD

**Issue by billygr** [wiedehopf/tar1090#28]
Hi,

Installation failed with last message 
mv: cannot stat '/usr/local/share/tar1090/html': No such file or directory

Solved by doing a 
sudo mkdir /usr/local/share/tar1090/html

And running again install.sh

Environment:
pi@raspberrypi ~ $ cat /etc/debian_version
9.11

**Comment by wiedehopf** [comment]
Should be fixed.

Thanks for reporting.
