### ISSUE TITLE
[QUESTION] Metrics

### ISSUE THREAD

**Issue by JoranJix** [wiedehopf/tar1090#289]
Is there a way we can grab metrics via prometheus?

**Comment by wiedehopf** [comment]
If you're running my readsb then /tar1090/data/stats.prom

**Comment by JoranJix** [comment]
> If you're running my readsb then /tar1090/data/stats.prom

Perfect. Thank you

**Comment by JoranJix** [comment]
Now im happy!
![image](https://github.com/wiedehopf/tar1090/assets/4482238/92b52cd8-e47c-4d29-8d98-db808dd5fa71)

**Comment by wendikristine** [comment]
@JoranJix what is the filter criteria you used to label emergencies?

**Comment by JoranJix** [comment]
I simply used "readsb_aircraft_emergency"
