### ISSUE TITLE
Banner bar does not go away for premium users

### ISSUE THREAD

**Issue by JeeveStobs** [wiedehopf/tar1090#293]
I am a premium user on Android 14 using the website and the banner bar at the top of the page does not go away when signed in. This area is where you can see ads as a non-premium user. Screenshot attached for illustration.
![Screenshot_20240303-130250](https://github.com/wiedehopf/tar1090/assets/15347708/c2c0d3df-2c68-40c1-8630-4bb738d46fa2)

This issue started sometime in the last 2 weeks.

**Comment by wiedehopf** [comment]
Talk to adsbexchange please.

**Comment by JeeveStobs** [comment]
Dang, I was hoping you were competent to fix this issue. My mistake!
