### ISSUE TITLE
No US sectionals or Terminal Area Charts

### ISSUE THREAD

**Issue by JonMurphy** [wiedehopf/tar1090#294]
I noticed the US Charts stopped working.  The background goes grey.

<img width="456" alt="Screen Shot 2024-03-07 at 9 03 38 AM" src="https://github.com/wiedehopf/tar1090/assets/15616372/42f33b64-426c-460a-8de1-d5720d7e2f0f">

I looked through the tar1090 Commits from December 2023 to today and I did not see any changes (but I have been accused of not seeing the obvious!).

I updated from **tar1090 on github (231215)** to **[tar1090 on github (240307)](https://github.com/wiedehopf/tar1090#tar1090)** and noticed those are gone.

<img width="385" alt="Screen Shot 2024-03-07 at 9 35 55 AM" src="https://github.com/wiedehopf/tar1090/assets/15616372/b65a6a06-e307-4dcf-a993-93c9b6ee8643">

**Am I missing a config setting?  did the US Charts get removed?**

**Comment by JonMurphy** [comment]
I found this in the code so it seems like these are still available but they do not appear for me.  This is where things go over my head. :exploding_head:


https://github.com/wiedehopf/tar1090/blob/e6e93fa9d30544107d78dffa86c119c187b2f272/html/layers.js#L337-L365

**Comment by wiedehopf** [comment]
The website providing these maps no longer exists.

**Comment by JonMurphy** [comment]
Ugh!
