### ISSUE TITLE
Plane icons not visible - ADS-B Unfiltered Plane Tracker 2.9 on Android 7.0

### ISSUE THREAD

**Issue by norbertwg** [wiedehopf/tar1090#297]
I am using ADS-B Unfiltered Plane Tracker 2.9 on Android 7.0, a great app. Since some time - I think this there was an automatic update - the icons of planes are no longer visible. Or to be more precise: almost not. When a plane is in the lower left corner, it is visible. But when it moves up or to the right, the icon disappears. It looks like there are layers, which do not cover the whole screen, but most of it and the plane icons are behind those layers.

For comparison I looked on a rather old and slow tablet running Android 6.0. When I start the app, I can see the different steps filling the screen. After map is displayed, I see plane icons. Then there are some other screen updates and after a while the screen shows map and all controls, but no longer the plane icons. Labels and track are shown, when enabled, only the plane icons disapperar.

**Comment by wiedehopf** [comment]
I'm not too concerned with old devices.
And that app might be using tar1090 but i have no way to know which version and so forth.

Just out of curiosity ... does this page work? https://adsb.lol/

**Comment by norbertwg** [comment]
Thanks for the very fast response. 
https://adsb.lol/ has the same behaviour on my tablet. 

I entered the issue here, because the app has a reference to this Github repository. As the page has the same behaviour as the app, I assume the problem is mainly caused by the old Android - or can you give me some hope, that contacting the developer of the app could help?

**Comment by wiedehopf** [comment]
Unlikely if he's just using tar1090
Curious again, does this work: https://adsb.lol/?nowebgl

**Comment by norbertwg** [comment]
That URL works fine, thanks a lot. So for me this can replace the app.
