### ISSUE TITLE
Planes are Mode S when beyond ~500 miles

### ISSUE THREAD

**Issue by alexkuck** [wiedehopf/tar1090#300]
I travel with my ADSB receiver. When I go beyond ~500 miles from my `readsb-set-location` all planes are listed as "Mode S" and I see only altitude, track, and speed. When I return to within ~500 miles of my `readsb-set-location`, the planes reappear as ADS-B and I see position data again.

Is this intended functionality?

**Comment by wiedehopf** [comment]
--max-range 0

**Comment by wiedehopf** [comment]
readsb also has a gpsd input if you care for an automatically updating tar1090 map.


This needs to be added to the readsb configuration:
```
--net-connector localhost,2947,gpsd_in
```

You can press H on the tar1090 map and it will follow the changing location automatically.
The dot and rings will be updated independently of pressing H.
