### ISSUE TITLE
Clarification on commands to get registration to show up in aircraft.json file

### ISSUE THREAD

**Issue by nils10** [wiedehopf/tar1090#302]
Hi, I would like the aircraft registrations to show up in the aircraft.json file. Reading online, I found these commands which should enable that: 
wget -O /usr/local/share/tar1090/aircraft.csv.gz https://github.com/wiedehopf/tar1090-db/raw/csv/aircraft.csv.gz
--db-file /usr/local/share/tar1090/aircraft.csv.gz
--db-file-lt /usr/local/share/tar1090/aircraft.csv.gz

I am only not sure what the full commands should be for the last two commands (using --db-file and --db-file-lt), could someone share that?

**Comment by nils10** [comment]
Answering my own question: Got it to work by adding in the /etc/default/readsb config file: --db-file /usr/local/share/tar1090/aircraft.csv.gz" to the RECEIVER_OPTIONS line. The complete line in my case then looked like this:
`RECEIVER_OPTIONS="--net-only --write-json-every 1 --db-file /usr/local/share/tar1090/aircraft.csv.gz"`

I've also tried adding --db-file-lt /usr/local/share/tar1090/aircraft.csv.gz to the same line, but that resulted in the following error, so I left that out for now:
tar1090[796]: No aircraft.json found in /run/readsb during the last 30 seconds! Try restarting dump1090 or reinstalling tar1090 if you switched dump1090 to readsb!

**Comment by wiedehopf** [comment]
Read the log, read the help for readsb: readsb --help
