### ISSUE TITLE
ADSB daily report showing low altitude near me

### ISSUE THREAD

**Issue by Mike-D-424** [wiedehopf/tar1090#307]
Is there a way for me to generate a daily report of aircraft near me (I have a pi feeder) below 1000 ft?

I am tired of low-flying helicopters shaking my house and wish to get a report showing the aircraft number, time, date, altitude, heading, etc. 

My skill level is limited therefore a very easy-to-implement solution is preferred.  

Thank you!

Michael

**Comment by RundesBalli** [comment]
Not exactly what you want, but you can send yourself a message when an aircraft passes over a certain area:
https://github.com/RundesBalli/adsbTelegramNotifier

Maybe this helps

**Comment by Mike-D-424** [comment]
Thank you

**Comment by Mike-D-424** [comment]
Thank you,  I am not smart enough to get this installed, configured, or 
to get reports generated.

------ Original Message ------
From: "kx1t" ***@***.***>
To: "wiedehopf/tar1090" ***@***.***>
Cc: "Mike-D-424" ***@***.***>; "Author" 
***@***.***>
Sent: 5/8/2024 08:30:07 AM
Subject: Re: [wiedehopf/tar1090] ADSB daily report showing low altitude 
near me (Issue #307)
