### ISSUE TITLE
Better icon for L2J - FA10 ?

### ISSUE THREAD

**Issue by Sovxx** [wiedehopf/tar1090#31]
A plane "L2J - FA10" looks like an A320.
It should rather look like a jet_swept.

I noticed in html/markers.js :
FA10 and L2J are not defined.
So I guess it is using a default icon.

By the way,
a plane "L3J - FA7X" looks OK (jet_swept).
FA7X and L3J are not defined either, but for some reason, it looks OK (jet_swept)...
Weird

**Comment by wiedehopf** [comment]
landplane 2 jet engines is very generic.

```
    'L2J-L': ['jet_nonswept', 1], // < 7t
    'L2J-M': ['airliner', 1], // < 136t                                                                                                
    'L2J-H': ['heavy_2e', 0.96], // > 136t

let CategoryIcons = {
    "A1" : ['cessna', 1],// < 7t
    "A2" : ['jet_swept', 0.94], // < 34t
    "A3" : ['airliner', 0.96], // < 136t
    "A4" : ['airliner', 1], // < 136t
    "A5" : ['heavy_2e', 0.92], // > 136t
    "A6" : ['hi_perf', 0.94],
    "A7" : ['helicopter', 1], 
```

Some other definitions that may apply.
FA10 and 20 are not explicitely defined.
