### ISSUE TITLE
how do you specify rtl device to use

### ISSUE THREAD

**Issue by akudlacek** [wiedehopf/tar1090#314]
I have 4 rtl dongles and i want to always select one in particular because i have another software that defaults to device 0. Seems like there isn't a way currently.

**Comment by AlNotSteve** [comment]
TAR1090 does not use your SDR.  You need to feed data from readsb / dump1090-fa to tar1090 to display.

Doco for those is quite clear and will show you how to specify the RTLSDR you want to use.

**Comment by akudlacek** [comment]
i found it that was helpful! sorry its been a while since i read through this.

for reference nano /etc/default/readsb to change the setting
