### ISSUE TITLE
Change the rings (size and number)

### ISSUE THREAD

**Issue by Jacopx** [wiedehopf/tar1090#316]
I would like to change the number and the distance between the distance rings, the default one are to big for my geographical restrictions. 
Maybe I haven't figured it how to change that, otherwise it could be a new feature.

![immagine](https://github.com/wiedehopf/tar1090/assets/14002538/cfe4d25d-0a0a-49a4-a3e4-345fbeca000e)

**Comment by RundesBalli** [comment]
`sudo nano /usr/local/share/tar1090/html/config.js`

Search for this, uncomment the variables and set it up like your wish:
https://github.com/wiedehopf/tar1090/blob/c70b0d0745bb6d40a39785f502055eccea7ed8c7/html/config.js#L197-L206

**Comment by Jacopx** [comment]
Thanks, it works!
