### ISSUE TITLE
Error on line 122, for fresh install on Debian

### ISSUE THREAD

**Issue by Json-181** [wiedehopf/tar1090#322]
Hi, running the tar1090/master/install script I'm receiving a error pointing to line 122, which states: [ERROR] Error in line 122 when executing: DB_VERSION_NEW=$(curl --silent --show-error "https://raw.githubusercontent.com/wiedehopf/tar1090-db/master/version") 

The current version at that time of writing this is: 3.14.1650

any thoughts? 
![image](https://github.com/user-attachments/assets/5d0b8ff2-0817-42a9-bc3e-5abce9276d77)
![image](https://github.com/user-attachments/assets/5bf63ff0-baef-4474-8101-91a533186762)

**Comment by wiedehopf** [comment]
Check again please.
