### ISSUE TITLE
404 error after update to current version.

### ISSUE THREAD

**Issue by rkarikari** [wiedehopf/tar1090#326]
Hello,
After updating to the latest version (3.14.1657) and restarting, I got the following error....

<img width="1678" alt="Screenshot 2024-08-03 at 12 58 42 PM" src="https://github.com/user-attachments/assets/d56a06c3-be5f-4530-a542-48f4a295cbf4">

uninstall and reinstall did not fix the issue.

Any help would be greatly appreciated.

**Comment by wiedehopf** [comment]
this has nothing to do with the version, don't confuse things and check what fails.

also completely unrelated to the normal operation of tar1090.
it fails cause you're changing stuff around.

**Comment by wiedehopf** [comment]
re-api is a feature for those people who can fix such a 404 on their own.
deactivate if you can't.

**Comment by wiedehopf** [comment]
Now you enabled --tar1090-use-api as a readsb option.
But it seems you failed to read the help for that option.

Good luck :)

**Comment by rkarikari** [comment]
I was not in the least  blaming anyone . 
I was merely listing the sequence of events.   Sorry,  if I was not clear in communicating.

I obviously had it working before the update. I simply failed to consider that I'd have to (repeat that process)  with each update.
I had a vague memory of a comment somewhere ...that  the  configuration  would be  maintained with an update.

Truly sorry...... and thank you.

All is well now.

**Comment by rkarikari** [comment]
Once more thanks. I do not take your time/work for granted.
Your assistance has been well appreciated.
Have a great day.

**Comment by wiedehopf** [comment]
No worries.

tar1090 will write webserver configuration files on every update. (as they could have changed in the repository)
One option is to not include those files but rather copy them.

Or make an extra file to include.

The reason for not including this by default is that it should be a conscious user decision to expose readsb API to the web.
While i'm not aware of any issues it's a consideration.

Building a new site? :)

**Comment by rkarikari** [comment]
Yes ...,and  I'm hoping I can get others to join in the fun. 
It's not popular in my part of the world.

Fingers crossed ... that changes soon.
:)

**Comment by wiedehopf** [comment]
For better consistency .. consider changing configure.sh
```
--net-ro-interval=0.05 --net-ro-interval-beast-reduce=0.12
```
Replace the ro-interval with these two arguments.

This is about how long stays in the buffer for certain connections before a packet is sent.
ro-interval won't matter but let's just put default 50 ms
while the beast reduce is gonna use 120 ms

**Comment by rkarikari** [comment]
Done!
Thank you so much.
