### ISSUE TITLE
How to get  history aircraft.json  like "history_0.json, history_1.json, ..., history_119.json"?

### ISSUE THREAD

**Issue by kevin4396** [wiedehopf/tar1090#329]
Hello!
I read the readsb/README-json.md ,and know that the history aircraft.json can be obtained ,from the link:https://github.com/wiedehopf/readsb/blob/dev/README-json.md#history_0json-history_1json--history_119json

**Problem**:However, when I pluged in rtlsdr, and started readsb+tar1090,  typed "**cd /run/readsb/**", I just found  aircraft.json without files like "history_0.json, history_1.json, ..., history_119.json",**I wait for 3 minutes ,but I still did't find  history aircraft.json.**
![0814](https://github.com/user-attachments/assets/310a9e6c-fda4-4857-803e-d473d3ef9697)

If I want to get the history files, **is there anything I should set**?

**Comment by kevin4396** [comment]
I use the default config ,like this 
![0814——2](https://github.com/user-attachments/assets/4bb132a1-cdb3-4196-b737-d012d8dde5b1)

**Comment by wiedehopf** [comment]
You shouldn't need them, they are not very useful.

But here you go, reinstall readsb newest version and add this command line argument.
```
--devel=legacy_history
```

**Comment by wiedehopf** [comment]
Oh the readme needs fixing.

Should just remove that section, no one should be using those files.
