### ISSUE TITLE
[Feature] Add aircraft count on tab

### ISSUE THREAD

**Issue by Bartholomew22** [wiedehopf/tar1090#333]
Add a count of aircraft on visible map similar to that of Piaware Skyaware page as seen on port 8080.  This allows on to monitor counts from multiple sites without shifting focus to a specific page.

![snippet](https://github.com/user-attachments/assets/368e2f82-cbf0-4966-8eb6-4c45f224d9b2)

**Comment by RundesBalli** [comment]
```bash
sed --follow-symlinks -i -E 's/.*PlaneCountInTitle =.*/PlaneCountInTitle = true;/' /usr/local/share/tar1090/html/config.js
```
If you want the message rate also:
```bash
sed --follow-symlinks -i -E 's/.*MessageRateInTitle =.*/MessageRateInTitle = true;/' /usr/local/share/tar1090/html/config.js
```

After that, CTRL+F5 in the tab:
![image](https://github.com/user-attachments/assets/e2eac18c-b8ef-4d26-9577-dc4308757e1e)


You're welcome
