### ISSUE TITLE
macOS compatibility & offline maps

### ISSUE THREAD

**Issue by northportio** [wiedehopf/tar1090#334]
I'd love to be able to use an SDR on a plane connected to my mac laptop and see where my plane is... if plane has no wifi.

**Comment by wiedehopf** [comment]
readsb the usual backend for tar1090 is limited to linux and not portable.
I suppose dump1090-fa might be able to be compiled on OS X and tar1090 can use that as a data source though generally not recommended.

I believe there is some stuff to somewhat easily run docker containers in a linux virtual machine ... as in Docker Desktop, maybe others. In that you could run <https://github.com/sdr-enthusiasts/docker-adsb-ultrafeeder>

**Comment by wiedehopf** [comment]
I don't care to explain this stuff really, just use this script if it's a ubuntu VM: <https://github.com/wiedehopf/adsb-scripts/wiki/Automatic-installation-for-readsb>

If you don't want it running, just stop the services, start them if you want it running.
```
systemctl disable --now readsb
systemctl disable --now tar1090
```
