### ISSUE TITLE
ADSB local low altitude loging

### ISSUE THREAD

**Issue by Mike-D-424** [wiedehopf/tar1090#342]
I wish to find a magic way for my existing ADS-B feed to create and (preferably e-mail me) a daily report, including aircraft ID, speed, heading, date, time, altitude, etc., of any aircraft lower than 1000 ft that my device receives.

I want this because I am tired of helicopters making my house shake since I live under their approach to a local airport.

I am not a coding or pi expert; therefore, a more straightforward and easier-to-implement solution is preferred.

Thank you, Michael

**Comment by RundesBalli** [comment]
It's not exactly what you want, but I'd still like to share this link: https://github.com/RundesBalli/adsbTelegramNotifier

**Comment by wiedehopf** [comment]
please note ADS-B shows uncorrected pressure altitude usually which is not MSL.
even if you get the geometric altitude from ADS-B, it's WGS84 referenced, not MSL for that you need converting to EGM96.

**Comment by Mike-D-424** [comment]
Thank you!

Michael Del Greco
***@***.***
56 Woodland Drive
Woodland Park, NJ 07424
