### ISSUE TITLE
[BUG] When tracking a plane in replay mode. Any change to the replay frame deselects the airplane.

### ISSUE THREAD

**Issue by littonj** [wiedehopf/tar1090#343]
Steps to reproduce.
1. Search for an aircraft by tail number in the search field
2. Select Isolate and Follow
3. Select Replay
4. Change any parameter in the replay frame
This will deselect the aircraft you searched for and close the aircraft frame.

Expected behavior: The aircraft should remain selected.

**Comment by littonj** [comment]
Additionally, deselecting the replay toggle also deselects the aircraft you are tracking. This should not be the case.

**Comment by wiedehopf** [comment]
tar1090 does not have a replay toggle.

You're looking at a fork.
