### ISSUE TITLE
Disabling range rings via config.js not working 

### ISSUE THREAD

**Issue by jaluebbe** [wiedehopf/tar1090#350]
I tried to disable the range rings to appear on default via config.js and SiteCircles = false; but it didn’t work.

**Comment by wiedehopf** [comment]
It does.
But browser cookie is overwriting if you toggled it before.

**Comment by jaluebbe** [comment]
I tried it using incognito windows on safari and chrome. In both cases, the variable in the config.js seems to be ignored. The range rings appear as soon I allow the browser to provide geolocation.

**Comment by wiedehopf** [comment]
F12 for dev console, check for js errors.

Also look at the config.js loading in the browser and confirm its content.

**Comment by wiedehopf** [comment]
Oh geolocation ... i guess i can check that.

**Comment by wiedehopf** [comment]
Using globe index with geolocation is a somewhat important detail to reproduce this issue.
It's quite a bit from the default config thus me testing / closing at first.
