### ISSUE TITLE
Filter out "planes" with 1 or few messages

### ISSUE THREAD

**Issue by giacomo892** [wiedehopf/tar1090#37]
I cannot find a way to do not show planes that has 1 message received at most. 
They are likely to be just receiver errors.
Like this: 
![image](https://user-images.githubusercontent.com/20860004/81148190-1ccaf080-8f7c-11ea-8af1-59e1a87aaabc.png)
The name starts with _ too.

**Comment by wiedehopf** [comment]
That shouldn't be shown with a proper decoder like dump1090-fa or readsb.
It's sometimes important to show everything the decoder will putin the json.

**Comment by giacomo892** [comment]
Hi, thanks for your reply.
I am using readsb right now

**Comment by wiedehopf** [comment]
Which version are you using?
I've just changed it for my dev branch, but generally that branch .... well does what i want it to do.
Don't expect that branch to be reasonable ;)

**Comment by giacomo892** [comment]
I'm using readsb 3.8.1 and tar1090 installed yesterday

**Comment by wiedehopf** [comment]
Could you elaborate on which readsb you installed exactly?

**Comment by giacomo892** [comment]
https://github.com/Mictronics/readsb

**Comment by wiedehopf** [comment]
3.8.3 isn't the current version.

Anyhow, aircraft with only one message shouldn't be in the json.

```
            if (a->messages < 2) { // basic filter for bad decodes
                continue;
            }
```

 Are you sure you aren't using a strange branch or sth ...

**Comment by wiedehopf** [comment]
correction, 3.8.1 isn't the current version 3.8.3 is.
But that's besides the point, i don't think this code was ever different.

**Comment by giacomo892** [comment]
I've just upgraded, idk why I was running 3.8.1
Will report. thanks!

**Comment by giacomo892** [comment]
Fine now, thanks!

**Comment by wiedehopf** [comment]
just out of curiosity, let's check the output for this command:

readsb --version

**Comment by giacomo892** [comment]
readsb --version
Mictronics v3.8.3

**Comment by giacomo892** [comment]
Should I run your fork?

**Comment by wiedehopf** [comment]
No you shouldn't.

Just puzzled how that 1 message plane made it into there.

**Comment by giacomo892** [comment]
:)

**Comment by giacomo892** [comment]
Continuing here so you already know my setup.
I've a strage issue. I've cleaned the cache and everything...
On Chrome I cannot see MLAT traffic, it just shows are Mode S
on the very same chrome, but incognito mode, it shows in yellow and as MLAT with position.

Any clue?

thanks

**Comment by wiedehopf** [comment]
Shift-N

**Comment by giacomo892** [comment]
Will try as soon I have traffic :D Thanks
