### ISSUE TITLE
Show only within certain range of receiver

### ISSUE THREAD

**Issue by PatrickS86** [wiedehopf/tar1090#40]
Hi,

Is it possible to only show airplanes within a certain range (5km for example) of the receiver on a new instance?

Thanks in advance, love tar1090!

**Comment by wiedehopf** [comment]
You're lucky, for some reason i didn't mind implementing it.
See the latest commit for the options.

Just as a note that you could also spin up a separate readsb instance and use --max-range in that 
https://github.com/wiedehopf/adsb-wiki/wiki/Building-readsb-from-source
