### ISSUE TITLE
B722 icon

### ISSUE THREAD

**Issue by beercity** [wiedehopf/tar1090#47]
B722 is using an icon for a small regional jet instead of a icon suitable for a jet of that size.

![image](https://user-images.githubusercontent.com/25492191/85436401-fe827980-b556-11ea-9b7f-b321dbd26936.png)

**Comment by wiedehopf** [comment]
Engine placement fits, icon is quite a bit bigger than for CRJs.

I'll increase the size a bit more, always a compromise.
