### ISSUE TITLE
Add second source

### ISSUE THREAD

**Issue by PatrickS86** [wiedehopf/tar1090#48]
Hi,

Is it possible to add a second source, for example, a friend of mine who runs dump1090 as well?

Thanks in advance,
Patrick

**Comment by wiedehopf** [comment]
No it's not.

You can take a look at https://github.com/wiedehopf/combine1090

Then in conjunction with that you can add another tar1090 instance as described in the readme.

Please don't ask here about how to set it up, i won't answer.
