### ISSUE TITLE
Map zoom buttons hidden if aircraft is selected

### ISSUE THREAD

**Issue by jbradsha** [wiedehopf/tar1090#5]
The zoom (+/-) buttons at the top left of the map are hidden by the information pane when an aircraft is selected. Can they be moved into view when an aircraft is selected?

Screenshots attached. Thanks!

![tar1080](https://user-images.githubusercontent.com/8588797/72993280-08a81c80-3ded-11ea-9892-4f5a5fc09139.png)

**Comment by wiedehopf** [comment]
yeah i'm aware ... i'll just fix it before someone else needs to remind me.
