### ISSUE TITLE
Button to select Helicopters - Feature Request

### ISSUE THREAD

**Issue by brauhausdc** [wiedehopf/tar1090#50]
Subject pretty much says it - I think it would be useful to have a button, similar to the current "U" button, which would toggle the display of just helicopters. I realize this may only be useful for those of us near metro areas that have a lot of helicopters flying around, but I'd appreciate it.

**Comment by wiedehopf** [comment]
Filter by type description: H

**Comment by brauhausdc** [comment]
Thanks. That works. Still would, imo, be "nice" to have a button.
