### ISSUE TITLE
Filter by array of callsigns (Feature Request)

### ISSUE THREAD

**Issue by viksra** [wiedehopf/tar1090#52]
In the "Filter by callsign" field, I would like to be able to type in an array of callsigns, i.e. FDX,UPS,ABX etc (separated by commas) to see all cargo flights of my choosing.

**Comment by wiedehopf** [comment]
FDX|UPS|ABX

already exists.

**Comment by viksra** [comment]
> FDX|UPS|ABX
> 
> already exists.

Thanks.

Anyone have others to add to the list? 

UPS|FDX|PAC|FX|CKK|ATN|GEC|WIG|CLU|AJT|GTI|CLX|VDA

Perhaps someone can go through this list and extract all of the cargo/shipping/freight aircraft codes? https://en.wikipedia.org/wiki/List_of_airline_codes_(0%E2%80%939)
