### ISSUE TITLE
Ability to have the Altitude ledgend (new feature)

### ISSUE THREAD

**Issue by BAZZZERH** [wiedehopf/tar1090#54]
Hi and first of all thanks for amazing software and help.... I have sorted the size issue that you helped with.... on another note I have been trying to grab the old altitude legend from the bottom of the piaware screen and add it to tar1090 script but to no avail... I wonder if you would consider adding it as an optional switch as was in the original piaware?

**Comment by jidanni** [comment]
Be sure to add reason for closing.
