### ISSUE TITLE
Filter by altitude broke in recent update

### ISSUE THREAD

**Issue by auroran-403** [wiedehopf/tar1090#66]
A recent update (likely the change to 200824) has caused the altitude filter to stop working (see attached). The behaviour is as if the button doesn't respond. Other filters work ok.
<img width="897" alt="Screen Shot 2020-08-26 at 22 33 29" src="https://user-images.githubusercontent.com/70308086/91384649-5904b400-e7ec-11ea-9c4d-00b35500d2de.png">

**Comment by wiedehopf** [comment]
In persistence mode tracks are filtered, not aircraft.
That's intentional, turn off persistence.
