### ISSUE TITLE
BLACK ORANGE LINE

### ISSUE THREAD

**Issue by Henry2o1o** [wiedehopf/tar1090#71]
Just one question, what does the dotted line mean?

![grafik](https://user-images.githubusercontent.com/6131799/95662927-f0269080-0b3a-11eb-909a-7c160eae68ab.png)

**Comment by wiedehopf** [comment]
Too much time between positions means dotted track.

**Comment by Henry2o1o** [comment]
I do not understand the lines?

![image](https://user-images.githubusercontent.com/6131799/95682833-dc853380-0be7-11eb-9c63-17fbb8372e32.png)

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/95682881-3128ae80-0be8-11eb-9ddd-a9c63ef47fbc.png)

No balloon flies like this?

**Comment by wiedehopf** [comment]
It's MLAT being very inaccurate.
Happens sometimes.

This is not the right place for these questions, please use the adsbexchange forum or discord.

**Comment by Henry2o1o** [comment]
ok, thanks
