### ISSUE TITLE
Add "branding" somewhere on the screen, so users can tell what site is being shared

### ISSUE THREAD

**Issue by jidanni** [wiedehopf/tar1090#72]
[Over and over](https://www.facebook.com/photo.php?fbid=3563830040306324&set=p.3563830040306324) users post screenshots from your site. But nobody can figure out what site it is. So have to ask, over and over.
This is because there is no "branding" anywhere in the frame.

Q: Well screenshots should include the URL bar. Then people can see what site this is.
A: Well most users will be using Full Screen, so there is no URL bar.

Q: Well tell them to mention what site it is in their posts.
A: I am reading read-only forums, and posts may have been made weeks earlier.

**Comment by wiedehopf** [comment]
This github page is not mainly about adsbexchange.
Go to the adsbexchange forum for such stuff.

You can make screenshots on other plane tracking websites without including their branding.

I really don't see the issue, people who don't mention their source are the issue.
They could also be taking screenshots of their local receiver, how do you know?
