### ISSUE TITLE
why 4294967.296

### ISSUE THREAD

**Issue by pan1021** [wiedehopf/tar1090#73]
data.now = ts[0] / 1000 + ts[1] * 4294967.296;  
Why is that number? Thank you

**Comment by wiedehopf** [comment]
It's a 64 bit unsigned integer timestamp in ms being converted to seconds.
As some browsers don't support uint64 i read it as 2 32 bit values and then do the appropriate calculation.
Doing the multiplication by 1<<32 and Division by 1000 separately results in an overflow.

**Comment by wiedehopf** [comment]
*doing the multiplication / division separately results in overflow, combining the two into one factor works.
