### ISSUE TITLE
Track Disappear on page reload/refresh

### ISSUE THREAD

**Issue by acebelowzero** [wiedehopf/tar1090#83]
Is it possible to keep the track display after a refresh or page reload?
I tried using persistent but it still loses data after a page reload or accessing it the site from a different computer.

**Comment by wiedehopf** [comment]
Then the history loading isn't working correctly.
You are talking about a local install?

**Comment by acebelowzero** [comment]
I installed tar1090 to my aws server. when I access it from my local computer I can see the track but when I refresh it the page the track and trailing line is gone.

**Comment by wiedehopf** [comment]
Check if the tar1090 service is running and you have files in /run/tar1090 ....
Also check the F12 browser console what it says about history loading.

**Comment by acebelowzero** [comment]
Before refresh
![before](https://user-images.githubusercontent.com/64754588/98162790-1a9c0d00-1e9f-11eb-8509-8a610dc24780.PNG)
After refresh
![after refresh](https://user-images.githubusercontent.com/64754588/98162831-27b8fc00-1e9f-11eb-814a-905f5d15cda6.PNG)


Console
![console](https://user-images.githubusercontent.com/64754588/98162902-3bfcf900-1e9f-11eb-8e73-eac59dfeed3d.PNG)

The history is loaded but it seems like its not grabbing the points for the line.

**Comment by acebelowzero** [comment]
Also when I go to /persist there no data popping up at all.

**Comment by wiedehopf** [comment]
Ah that's on purpose probably because it's a TIS-B track.

**Comment by wiedehopf** [comment]
I'd have to check.
Does it do it for all tracks?

**Comment by acebelowzero** [comment]
Yes all tracks.

**Comment by wiedehopf** [comment]
Link it please.

**Comment by wiedehopf** [comment]
If possible.

**Comment by acebelowzero** [comment]
Does TIS-B track not save in history?

**Comment by acebelowzero** [comment]
I am not sure what you mean to "link it" would you like the link the site?

**Comment by wiedehopf** [comment]
Yes.

**Comment by acebelowzero** [comment]
Unfortunately this is a private site.
I would you need your public IP to allow only you.

**Comment by wiedehopf** [comment]
Message me on the adsbexchange discord then.
https://discord.com/invite/UEXSqDh

**Comment by wiedehopf** [comment]
Problem was: field "seen" was missing so tar1090.sh ignored all aircraft.json entries.

**Comment by dxmekch** [comment]
Since the latest update I have the same problem

**Comment by wiedehopf** [comment]
No you don't have the same problem, you have the same symptom.
Your problem is likely with lighttpd.
Did you try updating just now, if not, do so.

**Comment by dxmekch** [comment]
Yes... just reupdated, still not displayed

**Comment by wiedehopf** [comment]
As described above i'll need a screenshot of the browser console (F12)

**Comment by wiedehopf** [comment]
Then check this:
```
ls /run/tar1090
```

**Comment by wiedehopf** [comment]
Or just join this discord and ask in tech-support: https://discord.com/invite/UEXSqDh
