### ISSUE TITLE
How to show readsb, and other data into one tar1090 instance or map.

### ISSUE THREAD

**Issue by acebelowzero** [wiedehopf/tar1090#84]

**Comment by wiedehopf** [comment]
tar1090 does not combine data, it all needs to be in a single json.
you could combine data with readsb.
SBS / basestation input for my readsb fork would probably work in inputing non-standard data.

Another method would be to tell tar1090 that the 2nd aircraft.json is 978 ... see the config.

Really the question is unspecific and i'm not sure i'm inclined to assist any further.
