### ISSUE TITLE
Tracking time (Feature Request)

### ISSUE THREAD

**Issue by jklnz** [wiedehopf/tar1090#9]
Hi,

I was just wondering if it was possible to add the time the plane has been tracked for on the left hand side bar when a plane is selected? 

Thanks

**Comment by wiedehopf** [comment]
When would you reset this time?

It's not really practical to do that.
Maybe just press K to enable track labels and check the oldest point in the track?

**Comment by jklnz** [comment]
Maybe on take off/landing?
